//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClube.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Sala = new HashSet<Sala>();
        }
    
        public int IDUsuario { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public Nullable<int> IDSala { get; set; }
        public string IDProfile { get; set; }
        public string Apelido { get; set; }
        public string Email { get; set; }
        public string Locale { get; set; }
        public string Sexo { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string CidadeEstado { get; set; }
        public Nullable<int> NumeroDenuncias { get; set; }
        public bool Verificado { get; set; }
        public Nullable<System.DateTime> DataHoraOnline { get; set; }
        public Nullable<System.DateTime> DataHoraUltimaAtualizacao { get; set; }
        public string Token { get; set; }
        public string ConnectionId { get; set; }
        public string VersaoAplicativo { get; set; }
        public string BSSIdWifi { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string IDsSalaNotificar { get; set; }
        public System.DateTime DataHora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sala> Sala { get; set; }
        public virtual Sala Sala1 { get; set; }
    }
}
